# Generated by Django 5.0.2 on 2024-02-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('language', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('plot', models.TextField()),
                ('rating', models.FloatField(default=50)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('actors', models.ManyToManyField(blank=True, null=True, to='actors.actor')),
                ('director', models.ManyToManyField(blank=True, null=True, to='directors.director')),
            ],
        ),
    ]
